apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api
  namespace: taskflow-prod
spec:
  replicas: 2
  strategy:                       
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: taskflow-api
  template:
    metadata:
      labels:
        app: taskflow-api
    spec:
      containers:
        - name: taskflow-api
          image: registry.gitlab.com/adlyatarisa/devops-group-5:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"